import random
from test import testEqual

# The rollDice function simulates the rolling of the dice. It
# creates a 2 dimensional list: each column is a die and each
# row is a throw. The function generates random numbers 1-6
# and puts them in the array.
def rollDice(dice, rolls):
    double_array = [[0 for i in range((int)(dice))] for j in range((int)(rolls))]
    for i in range(0, len(double_array)):
        for j in range(0, len(double_array[i])):
            double_array[i][j] = (int)(random.random()*6 + 1)
    return double_array


# This function takes a 2D array (which can be generated by rollDice)
# and sums the value of all the dice in each row. It returns a 1
# dimensional array with the sum of each throw.
# Example:
# double_array: [[1, 5, 6],[2, 3, 1],[1, 3, 3]]
# sumOfRoll should return: [12, 6, 7]
def sumOfRoll(double_array):
